[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
http = "1.2.0"
serde = { version = "1.0.219", features = ["derive"] }
diesel = { version = "2.2.8", features = ["postgres"] }
dotenvy = "0.15.7"
